/** @type {import('tailwindcss').Config} */
// CoFun — "Luminous Play" design system (exported from Stitch).
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  theme: {
    extend: {
      colors: {
        background: '#f9f9ff',
        'on-background': '#181c23',
        surface: '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-dim': '#d7dae5',
        'surface-gray': '#F5F7F9',
        'surface-variant': '#dfe2ed',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#ebedf9',
        'surface-container-high': '#e5e8f3',
        'surface-container-highest': '#dfe2ed',
        'surface-tint': '#006a6a',
        'on-surface': '#181c23',
        'on-surface-variant': '#3e4949',
        'inverse-surface': '#2c3039',
        'inverse-on-surface': '#eef0fc',
        outline: '#6e7979',
        'outline-variant': '#bdc9c8',
        primary: '#006767',
        'on-primary': '#ffffff',
        'primary-container': '#018282',
        'on-primary-container': '#f3fffe',
        'primary-fixed': '#92f2f2',
        'primary-fixed-dim': '#75d6d5',
        'on-primary-fixed': '#002020',
        'on-primary-fixed-variant': '#004f50',
        'inverse-primary': '#75d6d5',
        secondary: '#805600',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffbd52',
        'on-secondary-container': '#734d00',
        'secondary-fixed': '#ffddaf',
        'secondary-fixed-dim': '#fcbb4e',
        'on-secondary-fixed': '#281800',
        'on-secondary-fixed-variant': '#614000',
        tertiary: '#416261',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5a7a7a',
        'on-tertiary-container': '#f3fffe',
        'tertiary-fixed': '#c6e9e9',
        'tertiary-fixed-dim': '#abcdcd',
        'on-tertiary-fixed': '#002020',
        'on-tertiary-fixed-variant': '#2c4c4c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'success-mint': '#27AE60',
        'growth-orange': '#E67E22',
      },
      fontFamily: {
        'display-lg': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        heading: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'section-gap': '80px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};
